FROM python:3.8.10

ENV PYTHONIOENCODING=utf-8
ENV TZ="Asia/Tokyo"
ENV LANG=C.UTF-8
ENV LANGUAGE=en_US:en_US

RUN apt-get update\
    && apt-get install -y cron\
    -y vim\
    tesseract-ocr \
    libtesseract-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#COPY test_cron /etc/cron.d/
COPY app /app

WORKDIR /app

RUN pip install -r requirements.txt
#CMD python manage.py
